export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_WALLETS_FOR_PAYMENT = 'GET_WALLETS_FOR_PAYMENTS';
export const CREATE_PAYMENT_TRANSACTION = 'CREATE_PAYMENT_TRANSACTION';
export const CREATE_CP_PAYMENT_TRANSACTION = 'CREATE_CP_PAYMENT_TRANSACTION';
export const CP_PAYMENT_TRANSACTION_STATUS = 'CP_PAYMENT_TRANSACTION_STATUS';

//MetaMask Action Types
export const LOAD_COMPLETE = "LOAD_COMPLETE";
export const UPDATE_PAYMENT_AMOUNT = "UPDATE_PAYMENT_AMOUNT";
export const TRANSACTION_UPDATE_UI = "TRANSACTION_UPDATE_UI";
export const TRANSACTION_UPDATE_CURRENT = "TRANSACTION_UPDATE_CURRENT";
export const TRANSACTION_SENT = "TRANSACTION_SENT";

//Transaction List Action Types
export const LOAD_USER_TRANSACTION_LIST = "LOAD_USER_TRANSACTION_LIST";
export const CONFIRM_TRANSACTION = "CONFIRM_TRANSACTION";
export const CHANGE_COIN_TYPE = "CHANGE_COIN_TYPE";


export const OPEN_NEW_WINDOW = "OPEN_NEW_WINDOW";