export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_WALLETS_FOR_PAYMENT = 'GET_WALLETS_FOR_PAYMENTS';
export const CREATE_PAYMENT_TRANSACTION = 'CREATE_PAYMENT_TRANSACTION'


//MetaMask Action Types
export const LOAD_COMPLETE = "LOAD_COMPLETE"
export const METAMASK_FETH_ACCOUNTS = ""