export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_WALLETS_FOR_PAYMENT = 'GET_WALLETS_FOR_PAYMENTS';
export const CREATE_PAYMENT_TRANSACTION = 'CREATE_PAYMENT_TRANSACTION';
export const CREATE_CP_PAYMENT_TRANSACTION = 'CREATE_CP_PAYMENT_TRANSACTION';
export const CP_PAYMENT_TRANSACTION_STATUS = 'CP_PAYMENT_TRANSACTION_STATUS';
export const CP_PAYMENT_LINK_UPDATE = "CP_PAYMENT_LINK_UPDATE";

//MetaMask Action Types
export const LOAD_COMPLETE = "LOAD_COMPLETE";
export const UPDATE_PAYMENT_AMOUNT = "UPDATE_PAYMENT_AMOUNT";
export const TRANSACTION_UPDATE_UI = "TRANSACTION_UPDATE_UI";
export const TRANSACTION_UPDATE_CURRENT = "TRANSACTION_UPDATE_CURRENT";
export const TRANSACTION_SENT = "TRANSACTION_SENT";

//Transaction List Action Types
export const LOAD_USER_TRANSACTION_LIST = "LOAD_USER_TRANSACTION_LIST";
export const CONFIRM_TRANSACTION = "CONFIRM_TRANSACTION";
export const CHANGE_COIN_TYPE = "CHANGE_COIN_TYPE";


export const OPEN_NEW_WINDOW = "OPEN_NEW_WINDOW";

export const GET_USER_PAYMENT_DATA = "GET_USER_PAYMENT_DATA";
export const GET_USER_WALLET_DATA = "GET_USER_WALLET_DATA";
export const WALLET_DATA_IS_LOADING = "WALLET_DATA_IS_LOADING";
//Referral Data
export const LOAD_REFERRAL_DATA = "LOAD_REFERRAL_DATA";
export const REFERRAL_DATA_IS_LOADING = "REFERRAL_DATA_IS_LOADING";
 

export const ADMIN_AUTHORIZATION = "ADMIN_AUTHORIZATION";
export const ADMIN_LOAD_PAYOUTS = "ADMIN_LOAD_PAYOUTS";
export const ADMIN_IS_PAYOUT_LOADING = "ADMIN_IS_PAYOUT_LOADING";
export const ADMIN_LOAD_UNPROCESSED_TRANSACTIONS = "ADMIN_LOAD_UNPROCESSED_TRANSACTIONS";
export const ADMIN_IS_TRANSACTIONS_LOADNG = "ADMIN_IS_TRANSACTIONS_LOADNG";
export const ADMIN_PROCESS_TRANSACTION = "ADMIN_PROCESS_TRANSACTION";
export const ADMIN_LOAD_USERS = "ADMIN_LOAD_USERS";
export const ADMIN_USERS_IS_LOADING = "ADMIN_USERS_IS_LOADING";
export const ADMIN_UPDATE_USER = "ADMIN_UPDATE_USER";
